---
  - name: 'Install MariaDB'
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
      - python3-dev
      - python3-pip
      - mariadb-server
      - mariadb-client
      - python3-mysqldb
      - python-mysqldb

  - name: "Generate Otobo User"
    mysql_user:
      name: otobo
      password: otobo 
      priv: '*.*:ALL,GRANT'
      state: present

  - name: "Copy Setting for MariaDB"
    copy:
      src: 50-server.cnf
      dest: /etc/mysql/mariadb.conf.d/50-server.cnf

  - name: Restarting the Database
    service: name=mariadb state=restarted